SDK-899: extend the TaskSetInterface
spryker-sdk/sdk-contracts pull request #26
Opened 2022-09-07 08:28 UTC by sergeyspryker

https://spryker.atlassian.net/browse/SDK-899

2022-09-14 10:26 UTC, vol4onok approved these changes

2022-09-16 11:38 UTC, pavelmaksimov25 requested changes
Please merge latest master branch changes

2022-09-16 11:38 UTC, pavelmaksimov25 commented on src/Entity/TaskSetInterface.php
> +     * - Overrides sub-tasks placeholders.
It's just a getter. Why it overrides something?

2022-09-16 11:38 UTC, pavelmaksimov25 commented on src/Entity/TaskSetInterface.php
> +     * - Overrides tags of sub-tasks command property.
It's just a getter. why doesn't this method just return a value but do something else? The same  for the rest of the methods with `makes` or `overrides` words in the specification

2022-09-16 12:50 UTC, pavelmaksimov25 commented on src/Entity/TaskSetInterface.php
> +     * - Gets the list of task set tasks.
`Gets` => `Returns`. The same for the rest.

2022-09-16 13:13 UTC, pavelmaksimov25 approved these changes

2022-09-16 13:15 UTC, pavelmaksimov25 approved these changes

2022-09-16 13:17 UTC, merged