Feature/sdk 907 contracts api doc
spryker-sdk/sdk-contracts pull request #27
Opened 2022-09-07 13:39 UTC by vol4onok

https://spryker.atlassian.net/browse/SDK-930

2022-09-12 12:17 UTC, sergeyspryker approved these changes

2022-09-14 13:00 UTC, pavelmaksimov25 requested changes

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/CommandInterface.php
> +     * - Supporting types: php, local_cli, local_cli_interactive.
Supporting types must be quoted. php => `php`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/CommandInterface.php
> +     * - Returns flag for a stop or continue execution if command failed.
Returns a flag based on which a task will be stopped or will continue working in case of command failure.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/ContextInterface.php
> +     * - Adds message for showing in the result.
Adds a message to be shown in the result.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/ContextInterface.php
> +     * - Possible values: ContextInterface::SUCCESS_EXIT_CODE, ContextInterface::FAILURE_EXIT_CODE
Please use full path and quote the values.  The same for the `setExitCode`, `getExitCodeMap` and `addExitCode`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/ContextInterface.php
> +     * - Returns current task name.
It returns `TaskInterface`, not a string.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/ContextInterface.php
> +     * - Structure: commandName:code
We don't need to describe, what it looks like inside. Please remove the `Structure` spec line.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/ErrorCommandInterface.php
> +     * - Returns message.
- `Returns message.` => `Returns an error message.`
- `Returns an empty string if non exists.`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/ExecutableCommandInterface.php
> +     * - Executes command method.
`Executes command method.` => `Executes a command.`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/Lifecycle/LifecycleInterface.php
> + * Provides based interface for Lifecycle.
Add `@see` tag with a http link to the lifecycle doc.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/Lifecycle/LifecycleInterface.php
> + * Use this interface for php tasks.
`Use this interface for php tasks to ... .`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/MessageInterface.php
> +     * - Returns verbosity for showing needed level.
`Returns verbosity for showing needed level.` => `Returns set up verbosity level.`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/PlaceholderInterface.php
> +     * - Shortcode for replacing values in string command
`Placeholder name.` => `Returns a placeholder name`. Placeholder is a value in this case, so it must be quoted.

And we don't need to provide a definition for the method description. Please replace line 18 with a http link to the doc that describes `placeholder`.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/PlaceholderInterface.php
> +     * - Returns configuration for Placeholder.
Placeholder => `placeholder`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/SettingInterface.php
> +     * - Returns setting name.
a bit confusing. Please, put more info or rename it to the `getName`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/SettingInterface.php
> +     * - Returns setting values.
Returns `null` if none exists.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/SettingInterface.php
> +     * - Returns strategy.
What strategy?

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/SettingInterface.php
> +     * - Supported types SettingInterface::STRATEGY_MERGE, SettingInterface::STRATEGY_REPLACE.
Please, quote values and use FQDN for classes in the doc block.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/SettingInterface.php
> +     * - Setting value has Initializer.
Initializer => `Initializer`. The same of the rest

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/TaskInterface.php
> +     * - Returns `true` if task is optional.
- Returns `true` if the task is marked as optional.
- Returns `false` otherwise.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/TaskInterface.php
> +     * - Returns successor.
A link to a `successor` definition must be provided.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/TaskInterface.php
> +     * - Returns lifecycle for the task.
Please provide a link to the lifecycle definition.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/TaskSetInterface.php
> +     * - The list can have reference to the task.
list => collection. As you used that word above.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/WorkflowInterface.php
> +     * - Returns workflow transaction statues.
statues => statuses

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Entity/WorkflowInterface.php
> +     * - Returns workflow transaction statues.
Please provide a list of statuses that can be returned if it is not long.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/ReportArrayConverterInterface.php
> +     * - Convert report data to array.
`Convert` => `Converts`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/ReportConverterInterface.php
> +     * - Convert sniffer report data to the report.
It is not only for the sniffer.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/ReportableInterface.php
> +     * - Returns a abstract report.
`Returns a abstract report.` => `Returns a report.`

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/ReportableInterface.php
> + * Provides report structure.
It doesn't look like it provides a report structure. Please, provide a description that explains how it uses.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/Violation/ViolationConverterInterface.php
> +     * - Converts sniffer report to the violation report.
it is not related to the sniffer

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/Violation/ViolationInterface.php
> +     * - Returns severety.
Returns severity level.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Report/Violation/ViolationInterface.php
> +     * - Support severity keys: ViolationInterface::SEVERITY_INFO, ViolationInterface::SEVERITY_WARNING, ViolationInterface::SEVERITY_ERROR.
Please, quote severity options.

2022-09-14 13:00 UTC, pavelmaksimov25 commented on src/Workflow/TransitionResolverInterface.php
> +     * - The resolver name that can be used in workflow configuration.
Returns the resolver name...

2022-09-14 13:07 UTC, vol4onok commented on src/Entity/ErrorCommandInterface.php
> +     * - Returns message.
the second one not needed

2022-09-15 07:38 UTC, vol4onok commented on src/Entity/SettingInterface.php
> +     * - Returns setting values.
It's wrong. we don't have a setting if it's null or doesn't exist.

2022-09-15 07:53 UTC, vol4onok commented on src/Entity/WorkflowInterface.php
> +     * - Returns workflow transaction statues.
it depends on concrete workflow

2022-09-15 10:57 UTC, pavelmaksimov25 approved these changes

2022-09-15 11:05 UTC, merged