SDK-1110 task manifest phase 2
spryker-sdk/sdk-contracts pull request #36
Opened 2022-11-11 10:14 UTC by sergeyspryker

2022-11-16 09:30 UTC, vol4onok commented on src/Enum/ValueTypeEnum.php
> +    public static function getAllValueTypes(): array
we don't need it in contracts

2022-11-17 12:08 UTC, vol4onok approved these changes

2022-11-17 12:14 UTC, vol4onok approved these changes

2022-11-17 12:15 UTC, vol4onok requested changes
see comment

2022-11-17 12:18 UTC, vol4onok commented on src/Enum/ValueTypeEnum.php
> +    public static function getAllValueTypes(): array
Or split this class static::TYPE_PATH,  static::TYPE_UUID, should be SettingValueTypeEnum extends ValueTypeEnum

2022-11-17 12:19 UTC, vol4onok commented on src/Enum/ValueTypeEnum.php
> +    public static function getAllValueTypes(): array
@pavelmaksimov25 We can do it now or in the next epic

2022-11-17 12:24 UTC, vol4onok approved these changes

2022-11-17 13:46 UTC, closed without merging

2022-11-17 13:46 UTC, sergeyspryker commented
After discussions decided to implement it in separate epic